import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import StyledSection from "@/components/styled-section.component";
import LegacyStyledSection from "@/components/legacy-styled-section.component";
import StyledH1 from "@/components/styled-h1.component";
import { Box, css, SxProps, ThemeProvider } from "@mui/material";
import { useTheme } from "@mui/material/styles";
import MainH1 from "@/components/main-h1.component";
import SomeLegacyStyledSection from "@/components/some-legacy-styled-section.component";
import { buttonStyle} from '@/components/styles'; // Import the styles


const inter = Inter({ subsets: ["latin"] });

const sx = css({
  backgroundColor: 'purple',
  padding: '20px',
  color: 'primary',
});


export default function Home() {
  const theme = useTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={`${styles.main} ${inter.className}`}>
        <StyledSection sx={{padding:'50px'}}><p>Some content</p></StyledSection>
        <SomeLegacyStyledSection><h1>Hello there</h1><button onClick={() => alert('clicked')}>Click</button></SomeLegacyStyledSection>
        <StyledH1>I are H1</StyledH1>
        <Box sx={{
          padding: theme.spacing(4),
          color: theme.palette.primary.main,
          backgroundColor: theme.palette.background.default}}
          >I are box</Box>

        <Box component='button' sx={buttonStyle}>I are booton</Box>
        <MainH1 title="Say hello"></MainH1>
      </main>
    </>
  );
}
